<a href="https://colab.research.google.com/github/MirnaHesham/test/blob/main/Bot_detctionipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import csv
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
!pip install tweepy
!pip install botometer
import tweepy
import botometer


In [ ]:
import numpy as np
from sklearn.metrics import precision_recall_fscore_support

In [ ]:
fields = ['id', 'screen_name', 'name', 'location','url','description', 'verified','followers_count','friends_count', 'favourites_count', 'statuses_count','created_at', 'originals_urls_ratio', 'originals_replies_ratio', 'originals_retweets_ratio', 'replies_quotes_ratio', 'replies_retweets_ratio', 'followed_screen_name', 'cap','is_bot']  
db = pd.read_csv('pixierose13_2_cleaned.csv', usecols=fields)

id =  db["id"]
screen_name = db["screen_name"]
name= db["name"]
location = db["location"]
url = db["url"]
description = db["description"]
verified = db["verified"]
followers_count = db["followers_count"]
friends_count = db["friends_count"]
favourites_count = db["favourites_count"]
statuses_count =db["statuses_count"]
created_at = db["created_at"]
originals_urls_ratio =db["originals_urls_ratio"]
originals_replies_ratio = db["originals_replies_ratio"]
originals_retweets_ratio = db["originals_retweets_ratio"]
replies_quotes_ratio = db["replies_quotes_ratio"]
replies_retweets_ratio = db["replies_retweets_ratio"]
followed_screen_name = db["followed_screen_name"]
cap = db["cap"]
isBot=db["is_bot"]

In [ ]:
fields = ['id', 'screen_name', 'name', 'location','url','description', 'verified','followers_count','friends_count', 'favourites_count', 'statuses_count','created_at', 'originals_urls_ratio', 'originals_replies_ratio', 'originals_retweets_ratio', 'replies_quotes_ratio', 'replies_retweets_ratio', 'followed_screen_name', 'cap']  
db = pd.read_csv('pixierose13_2_followers.csv', usecols=fields)

id_1 =  db["id"]
screen_name_1 = db["screen_name"]
name_1= db["name"]
location_1 = db["location"]
url_1 = db["url"]
description_1 = db["description"]
verified_1 = db["verified"]
followers_count_1 = db["followers_count"]
friends_count_1 = db["friends_count"]
favourites_count_1 = db["favourites_count"]
statuses_count_1 =db["statuses_count"]
created_at_1 = db["created_at"]
originals_urls_ratio_1 =db["originals_urls_ratio"]
originals_replies_ratio_1 = db["originals_replies_ratio"]
originals_retweets_ratio_1 = db["originals_retweets_ratio"]
replies_quotes_ratio_1 = db["replies_quotes_ratio"]
replies_retweets_ratio_1 = db["replies_retweets_ratio"]
followed_screen_name_1 = db["followed_screen_name"]
cap_1 = db["cap"]

In [ ]:
print(screen_name)
print(screen_name_1)

In [ ]:
screen_name_1[5]

'XQsme8'

In [ ]:
#Edit the cap Score 
captry= cap
capEdit=[]
for i in captry:
  if i == 'None':
    capEdit.append(900)
  else:
    capEdit.append(i)


capUpdate=[]
for i in capEdit:
  if i == 900:
    capUpdate.append(9555555559)
  else:
    if float(i) >= 0.8:
      capUpdate.append(1)
    else:
      capUpdate.append(0)

len(capUpdate)
print(capUpdate)

df = pd.read_csv("pixierose13.csv")
df["CAP_U"] = capUpdate
df.to_csv("pixierose13.csv", index=False)

In [ ]:
featureVec=[]
for i in range(0,len(id)):
  smallfeatureVec=[]
  smallfeatureVec.append(screen_name[i])
  smallfeatureVec.append(originals_urls_ratio[i])
  smallfeatureVec.append(originals_replies_ratio [i])
  smallfeatureVec.append(originals_retweets_ratio [i])
  smallfeatureVec.append(replies_quotes_ratio [i])
  smallfeatureVec.append(replies_retweets_ratio [i])
  featureVec.append(smallfeatureVec)


featureVec_1=[]
for i in range(0,len(id_1)):
  smallfeatureVec=[]
  smallfeatureVec.append(screen_name_1[i])
  smallfeatureVec.append(originals_urls_ratio_1[i])
  smallfeatureVec.append(originals_replies_ratio_1 [i])
  smallfeatureVec.append(originals_retweets_ratio_1 [i])
  smallfeatureVec.append(replies_quotes_ratio_1 [i])
  smallfeatureVec.append(replies_retweets_ratio_1[i])
  featureVec_1.append(smallfeatureVec)


In [ ]:
featureVec_all=[]

for i in featureVec:
  featureVec_all.append(i)

for i in featureVec_1:
  featureVec_all.append(i)

In [ ]:
len(featureVec_all)

26010

In [ ]:
print(featureVec)
print(featureVec_1)


print(len(featureVec))
print(len(featureVec_1))


[['Jacfam2', 1.3387096774193548, 1.3387096774193548, 0.7094017094017094, 0.0, 0.5299145299145299], ['Hadi75968252', 0.6666666666666666, 1.6, 8.0, 0.08620689655172414, 5.0], ['ShullBrian', 1.4444444444444444, 0.5, 0.104, 0.4642857142857143, 0.208], ['sylzach1', 4.0, 1.0, 0.020408163265306117, 0.0, 0.020408163265306117], ['Republicantrai1', 79.0, 1.0463576158940395, 5.851851851851853, 10.066666666666666, 5.592592592592593], ['plumb_sue', 6.4, 1.1034482758620692, 0.32, 0.4603174603174603, 0.29], ['Floria6889', 0.0, 0.0, 0.0, 0.0, 0.0], ['RhumbaBetty', 0.0, 1.0, 0.01015228426395939, 0.0, 0.01015228426395939], ['m123IKI', 0.0, 0.0, 0.0, 0.0, 0.0], ['jessicathamess', 1.8, 1.2857142857142858, 0.371900826446281, 1.09375, 0.2892561983471074], ['BustersBrew', 3.8125, 1.1730769230769231, 0.4841269841269841, 4.0, 0.4126984126984127], ['JoshuaW94538152', 2.333333333333333, 2.0, 0.07777777777777778, 1.1666666666666667, 0.03888888888888889], ['Prosperous1776', 1.1428571428571428, 2.5454545454545454, 

In [ ]:
featureVec[0]

In [ ]:
g= nx.Graph()

In [ ]:
for i in screen_name:
  g.add_node(i)


for i in screen_name_1:
  g.add_node(i)

#add pixi itself
g.add_node(followed_screen_name[0])

In [ ]:
index=0
for x in screen_name:
  g.add_edge(x,followed_screen_name[index])
  index=index+1

  
index=0
for x in screen_name_1:
  g.add_edge(x,followed_screen_name_1[index])
  index=index+1


In [ ]:
listnodes=[]
for x in nx.nodes(g):
  listnodes.append(x)

In [ ]:
filename = 'Nodes.csv'
with open(filename, 'w') as csvfile:  
  # creating a csv writer object  
  csvwriter = csv.writer(csvfile)
  for i in range(0, len(listnodes)):
    csvwriter.writerow([listnodes[i]])

In [ ]:
listEdges=[]
for i in nx.edges(g):
  listEdges.append(i)

In [ ]:
filename = 'Edges.csv'
with open(filename, 'w') as csvfile:  
  # creating a csv writer object  
  csvwriter = csv.writer(csvfile)
  for i in range(0, len(listEdges)):
    csvwriter.writerow([listEdges[i]])

In [ ]:
All_nebs=[]
for x in nx.nodes(g):
  Neighbors=[]
  for i in nx.all_neighbors(g,x):
    Neighbors.append(i)
  All_nebs.append(Neighbors)

In [ ]:
filename = 'Neighbors.csv'
with open(filename, 'w') as csvfile:  
  # creating a csv writer object  
  csvwriter = csv.writer(csvfile)
  fields = ['Node','Neighbors']
  csvwriter.writerow(fields)

  for i in range(0, len(All_nebs)):
    csvwriter.writerow([listnodes[i],All_nebs[i]])    

In [ ]:
Feat_Node=[]
for x in listnodes:
  once=1
  for f in featureVec_all:
    if f[0]== x and once==1:
      #print(f)
      Feat_Node.append(f)
      once=once+1

In [ ]:
len(Feat_Node)

In [ ]:
Tany_Edited=[]
for x in Feat_Node:
  Edited=[]
  Edited.append(x[1])
  Edited.append(x[2])
  Edited.append(x[3])
  Edited.append(x[4])
  Edited.append(x[5])
  Tany_Edited.append(Edited)

In [ ]:
O_url=[]
O_rep=[]
O_ret=[]
Rep_quot=[]
Rep_ret=[]

for x in Feat_Node:
  Edited=[]
  O_url.append(x[1])
  O_rep.append(x[2])
  O_ret.append(x[3])
  Rep_quot.append(x[4])
  Rep_ret.append(x[5])

In [ ]:
len(Tany_Edited)

In [ ]:
len(O_rep)

In [ ]:
filename = 'Node_Features.csv'
with open(filename, 'w') as csvfile:  
  # creating a csv writer object  
  csvwriter = csv.writer(csvfile)
  fields = ['Node','Features']
  csvwriter.writerow(fields)

  for i in range(0, len(listnodes)):
    csvwriter.writerow([listnodes[i],Tany_Edited[i]])     

In [ ]:
filename = 'Node_Details.csv'
with open(filename, 'w') as csvfile:  
  # creating a csv writer object  
  csvwriter = csv.writer(csvfile)
  fields = ['Node','Features','Neighbors']
  csvwriter.writerow(fields)

  for i in range(0, len(listnodes)):
    csvwriter.writerow([listnodes[i],Tany_Edited[i], All_nebs[i]])   

In [ ]:
filename = 'Node_Info.csv'
with open(filename, 'w') as csvfile:  
  # creating a csv writer object  
  csvwriter = csv.writer(csvfile)
  fields = ['screen_name', 'originals_urls_ratio', 'originals_replies_ratio', 'originals_retweets_ratio', 'replies_quotes_ratio', 'replies_retweets_ratio', 'neighbors']
  csvwriter.writerow(fields)

  for i in range(0, len(listnodes)):
    csvwriter.writerow([listnodes[i], O_url[i],O_rep[i],O_ret[i],Rep_quot[i],Rep_ret[i],All_nebs[i]])   

In [ ]:
fields = ['label']  
db = pd.read_csv('result.csv', usecols=fields)
lab =  db["label"]

In [ ]:
All_labels=[]
for i in isBot:
  All_labels.append(i)


for x in lab:
  All_labels.append(x)

In [ ]:
filename = 'Inshallah_Info.csv'
with open(filename, 'w') as csvfile:  
  # creating a csv writer object  
  csvwriter = csv.writer(csvfile)
  fields = ['screen_name','label', 'originals_urls_ratio', 'originals_replies_ratio', 'originals_retweets_ratio', 'replies_quotes_ratio', 'replies_retweets_ratio', 'neighbors','neighb_label']
  csvwriter.writerow(fields)

  for i in range(0, len(listnodes)):
    csvwriter.writerow([listnodes[i],All_labels[i], O_url[i],O_rep[i],O_ret[i],Rep_quot[i],Rep_ret[i],All[i],labels_As_neighbors[i]])   

In [ ]:
print(len(lab)) 
print(len(cap))

In [ ]:
print(len(All_nebs))
print(len(All_labels))
print(len(listnodes))

In [ ]:
labels_As_neighbors=[]
current_labels=[]

for i in range(0,18903):
  print('=================================================')
  print(listnodes[i])
  print('=================================================')
  current_labels=[]
  for x in range(0,len(All_nebs[i])): 
    #print(All_nebs[i][x])
    index= int(listnodes.index( All_nebs[i][x]))
    current_labels.append((All_labels[index])) 
    #print(All_labels[index])
  labels_As_neighbors.append(current_labels)

In [ ]:
len(labels_As_neighbors)

In [ ]:
print(len(labels_As_neighbors[993]))
print(len(All_nebs[993]))
print(listnodes[993])

In [ ]:
labels_As_neighbors[993]

In [ ]:
All_nebs[993]

In [ ]:
print(nx.degree(g,followed_screen_name[0]))
print(nx.info(g))
print(nx.nodes(g))
print(nx.edges(g))

In [ ]:
Dist_id=[]
nodesInr=[]

for i in range(988,18903):
  index=-1
  for x in screen_name_1:
    index=index+1
    if x== listnodes[i]:
      Dist_id.append(id_1[index])
      nodesInr.append(listnodes[i])
      break

In [ ]:
print(Dist_id)
print(nodesInr)

In [ ]:
Dist_id.append(1000807582825500672)
nodesInr.append('Porouje1')

In [ ]:
for x in nx.nodes(g):
  print(nx.degree(g,x))

In [ ]:
for x in nx.nodes(g):
  print("==================================================")
  print('Neighbors of ', x )
  print("==================================================")
  for i in nx.all_neighbors(g,x):
    print(i)

In [ ]:
for x in nx.edges(g):
  print(x)

In [ ]:
plt.figure(100,figsize=(100,100)) 
nx.draw(g)
plt.show()

In [ ]:
fields = ['iteration_0'] 
db = pd.read_csv('Results_ACA.csv', usecols=fields)
ACA_socres = db[fields]

In [ ]:
fields = ['Final_Res'] 
db = pd.read_csv('Results_ICA.csv', usecols=fields)
ICA_socres = db[fields]

In [ ]:
ACA_socres

In [ ]:
changes=[]
chan_1=0
chan_0=0
was0_became1=0
was1_became0=0
indexOfboty=[]


for i in range(0,len(ICA_socres)):
  if ICA_socres[i]== ACA_s[i]:
    changes.append(1)
    chan_0=chan_0+1
  else:
    changes.append(0)   
    chan_1=chan_1+1
    if ICA_socres[i]==1:
      was1_became0=was1_became0+1
      indexOfboty.append(i)
    else:
      was0_became1=was0_became1+1

names=[]
for i in indexOfboty:
  names.append(screen_name[i])
print(names)

KeyError: ignored

In [ ]:
con=[]
for i in range(0,200):
  con.append(label[i])

In [ ]:
precision_recall_fscore_support(capaa, con,1)

(array([0.55      , 0.62222222]),
 array([0.13924051, 0.92561983]),
 array([0.22222222, 0.74418605]),
 array([ 79, 121]))

In [ ]:
changes=[]
chan_1=0
chan_0=0
was0_became1=0
was1_became0=0


for i in range(0,len(converg)):
  if label[i]==converg[i]:
    changes.append(1)
    chan_0=chan_0+1
  else:
    changes.append(0)   
    chan_1=chan_1+1
    if label[i]==1:
      was1_became0=was1_became0+1
    else:
      was0_became1=was0_became1+1

In [ ]:
print("For 100 iterations on 75 percent : ")
print("------------------------------------------------------------")
print("number of unchanged labels     = ",chan_0)
print("number of changed labels       = ",chan_1)
print("percentage of unchanged labels = ", chan_0/len(changes))
print("percentage of changed labels   = ", chan_1/len(changes))
print("was 1 and became zero          = ", was1_became0)
print("was zero and became 1          = ", was0_became1)
print("perentage 1 and became zero    = ", was1_became0/ chan_1)
print("percentage zero and became 1   = ",was0_became1/ chan_1)

In [ ]:
Bot_label=0
Human_label=0

for i in range(0,200):
  if label[i]==1:
    Bot_label=Bot_label+1
  else:
    Human_label=Human_label+1


Bot_Cap=0
Human_Cap=0

for i in range(0,200):
  if converg[i]==1:
    Bot_Cap=Bot_Cap+1
  else:
    Human_Cap=Human_Cap+1


Bot_ica=0
Human_ica=0

for i in range(0,len(capy)):
  if capy[i]==1:
    Bot_ica=Bot_ica+1
  else:
    Human_ica=Human_ica+1

In [ ]:
changes=[]
chan_1=0
chan_0=0
was0_became1=0
was1_became0=0
indexOfboty=[]


for i in range(0,len(capy)):
  if converg[i]==capy[i]:
    changes.append(1)
    chan_0=chan_0+1
  else:
    changes.append(0)   
    chan_1=chan_1+1
    if converg[i]==1:
      was1_became0=was1_became0+1
      indexOfboty.append(i)
    else:
      was0_became1=was0_became1+1

names=[]
for i in indexOfboty:
  names.append(screen_name[i])
print(names)

In [ ]:
print(indexOfboty)

In [ ]:
matches=[]
for i in changes:
  if i==1:
    matches.append('Yes')
  else:
    matches.append('No')


In [ ]:
with open('200_sample.csv', 'w', ) as myfile:
   wr = csv.writer(myfile)
   wr.writerow(['screen_name', 'model_score', 'boto_score', 'match'])
   for i in range(0,200):
     wr.writerow([screen_name[i], converg[i], capy[i],  matches[i]    ])

In [ ]:
print("Compare 200 sample between botometer and ICA: ")
print("number of unchanged labels                    = ",chan_0)
print("number of different labels                    = ",chan_1)
print("percentage of unchanged labels                = ", chan_0/len(changes))
print("percentage of changed labels                  = ", chan_1/len(changes))
print("1 in ICA and  zero in boto                    = ", was1_became0)
print("zero in ICA and  1 in boto                    = ", was0_became1)
print("perentage Bot in ICA and Human in boto        = ", was1_became0/ chan_1)
print("percentage Human in ICA and Bot in boto       = ",was0_became1/ chan_1)

In [ ]:
print(Bot_ica)
print(Human_ica)
print(Bot_Cap)
print(Human_Cap)
print(Bot_label)
print(Human_label)

In [ ]:
print('Bots in iterative : ',Bot_ica,'        Human in iterative : ',Human_ica)
print('Bots in Cap       : ',Bot_Cap,'        Human in Cap       : ',Human_Cap)
print('Bots in label     : ',Bot_label,'        Human in label     : ',Human_label)

print('Bots % in iterative : ',Bot_ica/200,'        Human  % in iterative : ',Human_ica/200)
print('Bots % in Cap       : ',Bot_Cap/200,'        Human  % in Cap       : ',Human_Cap/200)
print('Bots % in label     : ',Bot_label/200,'        Human  % in label     : ',Human_label/200)


Bots in iterative :  121         Human in iterative :  79
Bots in Cap       :  126         Human in Cap       :  74
Bots in label     :  180         Human in label     :  20
Bots % in iterative :  0.605         Human  % in iterative :  0.395
Bots % in Cap       :  0.63         Human  % in Cap       :  0.37
Bots % in label     :  0.9         Human  % in label     :  0.1


In [ ]:
# trials to intiate Edges and nodes on normal lists

"""
index =0
Nodelist=[]
for i in screen_name:
  N= Node(i,featureVec[index])
  Nodelist.append(N)
  index=index+1

Edgelist=[]
for i in Nodelist:
  E= Edge(i,pixi)
  Edgelist.append(E)

for i in Edgelist:
  print(i.from_node.node_id, "                 ",i.to_node.node_id )


for i in Nodelist:
  print(i.node_id)
  print(i.feature_vector) 

  """